version: '3'
services:
  db:
    container_name: postgresql
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmpDatabase:/var/lib/postgresql/data
  api:
    image: controle-garrafao-api:latest
    build: .
    volumes:
      - ./controleGarrafao:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
