version: '3'
services:
  db:
    container_name: postgresql
    image: postgres
    volumes:
      - ../postgresData/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  web:
#    image: controle-garrafao:latest
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    volumes:
#      - .:/app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
